name: Accessibility Issue
description: Document an accessibility issue and any actions taken to correct it
title: "<jira ticket number>: <title>"
body:
- type: markdown
  attributes:
    value: "# Problem Overview"
- type: textarea
  id: problem
  attributes:
    label: Problem
    description: How the Problem negatively impacts site accessibility
  validations:
    required: true
- type: textarea
  id: targets
  attributes:
    label: Target(s)
    description: Specific code elements or attributes affected by the Problem
  validations:
    required: true
- type: input
  id: prevalence
  attributes:
    label: Number of URLs affected
    description: The number of unique site URLs impacted by the Problem
  validations:
    required: false
- type: textarea
  id: examples
  attributes:
    label: Examples of affected URL(s)
  validations:
    required: true
- type: textarea
  id: recommended_correction
  attributes:
    label: Recommended correction
    description: Recommended action to correct the Problem
  validations:
    required: true
- type: textarea
  id: code_to_correct
  attributes:
    label: Link to code to be corrected
    description: A link to the specific code elements or attributes affected by the Problem in GitHub
  validations:
    required: true
- type: markdown
  attributes:
    value: "# Change Overview" 
- type: textarea
  id: visual_observation
  attributes:
    label: Visual
    description: Visual evidence of the recommended change (may include images)
  validations:
    required: false
- type: textarea
  id: markup_observation
  attributes:
    label: Markup
    description: Markup evidence of the recommended change (may include images)
  validations:
    required: false
